name: Deploy Symfony to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Adjust this to your Symfony project's PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Prepare SSH
        run: |
          mkdir -p /tmp/ssh
          touch /tmp/ssh/known_hosts
          echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmUJnGMIHdKqi1s9KzHPAYWCDzM9mSCYkTUDxrW8QZbTvbB0wjmnhdqXa/tzIGQup0ylIu2FUeEt0Y7ttn119W49bjKoG/YZFCaUH2aRa+/DJWPO1Nyj36RPLl46iyUdBiOHanrBwWcyPsW/JH2uEmIKoT2YvIndZNYu9vdU5D/fS9PSMXFfblFWlFlZQu+ljQGSsLw+Pdofs0R3P/jmfOaUFXFjBbRlh6wAepwgVN6VzDbhGlzaYkjYBBXo8WHmlSY3vUUCZEFaf0/NDvneC7BX/WKlCcoYtPMZVErPLZKsgP6VkwQ0kIk2SThkVYgLFLbuH1xtYGxPzAKlDjdHphTEoc7r0C131gIjvTEJf6cAuSrbg7dnNwvjI1ATc1FlDFXrIUG6TV2ckr7UPaJfjp9u4tfcneOWLIxRANCPelwltoulkaoGvUaqucHYdqnF1lz4QLnDXU0sE8YhUkK71oZX3pbdkX0VGbgKvcf1RYOUX4oFxAukOEXweBiuvzNK8= u490557680@us-phx-web1009.main-hosting.eu' >> /tmp/ssh/known_hosts

      - name: Build Symfony app
        run: php bin/console cache:clear --env=prod

      - name: Set SSH password for sshpass
        run: echo "export SSHPASS=${{ secrets.HOSTINGER_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to Hostinger using SSH
        run: |
          sshpass -e scp -r ./ u490557680@alenhuric.com:/public_html/symfony
