name: Deploy Symfony Project to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hostinger
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Use the PHP version compatible with your Symfony project

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }} # Add your Hostinger SSH private key to GitHub Secrets

      - name: SSH into the remote server
        run: |
          ssh -p 65002 -i /Users/Alen/alenkey u490557680@alenhuric.com "cd /home/u490557680/public_html/symfony && git pull origin master && php bin/console cache:clear --env=prod && php bin/console doctrine:migrations:migrate --no-interaction"
