name: Deploy Symfony to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Adjust this to your Symfony project's PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Prepare SSH
        run: |
          mkdir -p /tmp/ssh
          touch /tmp/ssh/known_hosts
          echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmUJnGMIHdKqi1s9KzHPAYWCDzM9mSCYkTUDxrW8QZbTvbB0wjmnhdqXa/tzIGQup0ylIu2FUeEt0Y7ttn119W49bjKoG/YZFCaUH2aRa+/DJWPO1Nyj36RPLl46iyUdBiOHanrBwWcyPsW/JH2uEmIKoT2YvIndZNYu9vdU5D/fS9PSMXFfblFWlFlZQu+ljQGSsLw+Pdofs0R3P/jmfOaUFXFjBbRlh6wAepwgVN6VzDbhGlzaYkjYBBXo8WHmlSY3vUUCZEFaf0/NDvneC7BX/WKlCcoYtPMZVErPLZKsgP6VkwQ0kIk2SThkVYgLFLbuH1xtYGxPzAKlDjdHphTEoc7r0C131gIjvTEJf6cAuSrbg7dnNwvjI1ATc1FlDFXrIUG6TV2ckr7UPaJfjp9u4tfcneOWLIxRANCPelwltoulkaoGvUaqucHYdqnF1lz4QLnDXU0sE8YhUkK71oZX3pbdkX0VGbgKvcf1RYOUX4oFxAukOEXweBiuvzNK8= u490557680@us-phx-web1009.main-hosting.eu' >> /tmp/ssh/known_hosts

      - name: Build Symfony app
        run: php bin/console cache:clear --env=prod

      - name: Set SSH private key
        run: |
          echo b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn NhAAAAAwEAAQAAAgEAs2XqmHUIhavINOzPzFRYTbsqo73RbBGTBiNeftuObZwbv2CoXcE7 jikGA6G/YGYMCWhRGEpMJmv9loLzwqSABRMlGbWhHhzB+IaTfPpoZRYqdb7MATXIveny/m YvZawIRkUPFPOpnLVytph1s8QUkFSlx7nOmdPw5VRpJU3QgfwDv6+Q9VjB5cMU5UmmaUrt yWx7ojyzsnX1eXVdnhaLR+LABiQL2h3oosoikXGmEYdTIZB/PLluHxxLqTvLyldhaWVzRS X0ZO08MPcM3zo6sFXowsS2Y7rr9riiF4VcaFWAnDLY4wmnvwJ7/LsQnEbKyKArjOUoJvqI wIM8MhDJUyGaXS4g3GmwxDTaZpL9gzXAJANsWaOd8CCmU0E9QkbiafeW/YxY2wBjMWGWXl 8POaqMIT+kMHVJ++sZYkNg5FSc3cvmlhGfqzeJtQX3XouX3ZPm+MK70V1xt7aM5Ey8ABOl 3i+sf5UIpW4+VaE8pjvoYo67bAbK4KjplBm1zPtUVXWIOX6+wyZVHDE1LwaWs24m3BsHgZ R3kJ16aGDZja6Hpd9NQsgqVIuJWlk17AQcP2jwfUj+x0Es09ISrjp0jR2iGHshnDaWbDNn JkrhZWHZUr/ZuLHcq6d52PbNjiyGgWN2zengxnZ0UZai9pYfnXKzhHJeXTJWE0ePtF8sUx cAAAdINFJMjjRSTI4AAAAHc3NoLXJzYQAAAgEAs2XqmHUIhavINOzPzFRYTbsqo73RbBGT BiNeftuObZwbv2CoXcE7jikGA6G/YGYMCWhRGEpMJmv9loLzwqSABRMlGbWhHhzB+IaTfP poZRYqdb7MATXIveny/mYvZawIRkUPFPOpnLVytph1s8QUkFSlx7nOmdPw5VRpJU3QgfwD v6+Q9VjB5cMU5UmmaUrtyWx7ojyzsnX1eXVdnhaLR+LABiQL2h3oosoikXGmEYdTIZB/PL luHxxLqTvLyldhaWVzRSX0ZO08MPcM3zo6sFXowsS2Y7rr9riiF4VcaFWAnDLY4wmnvwJ7 /LsQnEbKyKArjOUoJvqIwIM8MhDJUyGaXS4g3GmwxDTaZpL9gzXAJANsWaOd8CCmU0E9Qk biafeW/YxY2wBjMWGWXl8POaqMIT+kMHVJ++sZYkNg5FSc3cvmlhGfqzeJtQX3XouX3ZPm +MK70V1xt7aM5Ey8ABOl3i+sf5UIpW4+VaE8pjvoYo67bAbK4KjplBm1zPtUVXWIOX6+wy ZVHDE1LwaWs24m3BsHgZR3kJ16aGDZja6Hpd9NQsgqVIuJWlk17AQcP2jwfUj+x0Es09IS rjp0jR2iGHshnDaWbDNnJkrhZWHZUr/ZuLHcq6d52PbNjiyGgWN2zengxnZ0UZai9pYfnX KzhHJeXTJWE0ePtF8sUxcAAAADAQABAAACABZCmy13uCr9+cW3bMFp5dsfUlcnAolqVNf6 I4uSKsYnDLpegAXCKGWnaXuh4mFPyEaSjx14eqJ52+mFLkIEr23xxjS+eNOHtfnkmQB1Ae cpLPOXTTEJP3NxSBmRDGiNRCmUAB8VbQJo8Wb+2/wGZJbUKg3yXFRyG/4Yz0M1uJ2oa76p Rk9rSAP+hOU+kkuWZJMNxvmGlrWaNW9wxMENAxNUa4dXibDy7R7l/gwWEgkyxXnwuBkM2U E6/ZhuNwdQeGHfmMIHx5+OYF2jChHY49dlkZA5YHhXhVgD6PkKL0Ey+tZm6MqjNBFbeY8O ly0NC7SBS2YcOTM8+yMIJbwAoTpeNXzsiXpokbPXxQ3JFfFFA2HhO9MyBP6fkamLShS2z7 JY1emB4Tl5NrTg6VmibR9EvfcASZN0KdGzYtqgRXAqPeyUgNWvSMoWDpNQXoc9Yv+eJliO tqitqaeGNWvJi7cexs0dgaOrfvQb/H31dz93SL58EJl5ilJn3pGJWWgHlJcpUNCXVxIl0d 1D4tLXkL6DRDhRbhK6ADLkYw1hwUgW5XmZpjSUiTGOs5ky5bfdOtQ/BN4L4C4poXKiyF3m CBRyJGLU21zJimDL6ewFAUJm78TeAGJ8p3AKqp13R7m4ylFUksF+x1VPpq8dm/FIj6SRfd LHInzMU3/gGHAynD8BAAABAC6rl2AswEuo9hdk4Sya/ry8UPUGDf/newKDHWqeqi2CDODP ypCCQ9NAop1mq43ZEjvo41RFuTTX676X1Z+bgOBmqqktXuIPbcwAYAcHMi4Y3Hwd3+bprE HVL5GEb5NplixBXykLYuQ8GG62JgIz21MwWE/6qHi7Lxm3tLSwHH4QFY0I8lxIAmYocxw4 DLNuqlChomXuw4BxNjoLNtWo6x5pe5Z5Efux5uV1UFi6zaXXu5eTFG0gzVKrLtM5eeHJk+ n/E7fwTpek4A0KF2ZyksYCDqh9h2CX3M/HHlTbtxYt5bvdRfXkwu0bUay9ZyfZspu7/qJD JGJaAmfY5B1zvxkAAAEBAOOUmls+xXsOJ8BHDJz1colHfSOu2SDIx38LUxg5f5pulPuZqb qF47XjkiKMp+hiOL9D+U29sqYnSaF+tqebWJd72KJQGaKuAoBsERCn3C/ysbdRs69ygUT3 6SohJ0pjny5GPqFsPiccq2qMGm0scFMFQR70DgsUvX3W8HabNQMEmK0cOVFU8+DI5Wawre 5n3eQiYHhJUKVjAJZJQzokGAa3JeSMPhm8qSxfcMEAap+iIjZ/54WzETevmom0+WE6/mMi is0tRDAND4JhjNX/EZLOTzN8jEw94o6hpsP+WVjbDq9xb80DAZTGW3XxqlY0wpyGmVhLEv QwNG6czr96Z6EAAAEBAMnM/1QhNbf7P1o6x3IzDnCjP5kri2iCSBgW34QxuNLYiIhifsQD Nu5RV7wCNAPfsmkqUg7YJPqqIVAieiYIRVu5rNCEKJC9O3N5hUQ0szfwULiB6yIrfQosU8 dSnfBan8dX8gZriStaK8mATgezYGRI0fRHITiqDO/b0Znx4JiXTQeit4PuvJttI9j+8NaX KIWGMivMCaTR6+7T6C3tsFRnl019tKJo8cP9t4ZctM1JFXUkvwq/34jPEJo/NjiclJOwIP gt9uk5E3VgA4RVD627L3B+57ySbFodUsCvsbm6ffH41hGB181HwFmDXv8Jy9Dv9qgTawUY hDI3xGkH37cAAAATYWxlbmh1cmtlQGdtYWlsLmNvbQ== > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Hostinger using SSH
        run: |
          ssh -o StrictHostKeyChecking=no u490557680@alenhuric.com "mkdir -p /public_html/symfony"
          scp -r ./ u490557680@alenhuric.com:/public_html/symfony
