name: Deploy Symfony to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Adjust this to your Symfony project's PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Prepare SSH
        run: |
          mkdir -p /tmp/ssh
          touch /tmp/ssh/known_hosts
          ssh-keyscan -t rsa alenhuric.com >> /tmp/ssh/known_hosts

      - name: Build Symfony app
        run: php bin/console cache:clear --env=prod

      - name: Deploy to Hostinger using SSH
        run: |
          sshpass -p ${{ secrets.HOSTINGER_PASSWORD }} scp -r ./ u490557680@alenhuric.com:/public_html/symfony
